# Общие параметры
# font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
font_size        12.0
enable_audio_bell yes
# hide_window_decorations yes
initial_window_position top_left_left

# Цвета (Адаптированы под Alan Wake 2 / Stage Lights)
# Фон: очень темный зелено-черный, как пол сцены в тени
background               #0b1210
# Текст: слегка приглушенный белый с мятным оттенком
foreground               #e0ebe8
# Курсор: ярко-оранжевый, как свет прожекторов сверху
cursor                   #ffae00
# Выделение: темно-бирюзовый
selection_background     #2d5c55
selection_foreground     #ffffff

# Цвета ANSI

# Black (Тени одежды и сцены)
color0  #1c2924
color8  #3a4f48

# Red (Приглушенный кирпичный/красный, акценты)
color1  #e05f45
color9  #ff7a63

# Green (Основной цвет тумана и света на сцене)
color2  #20c278
color10 #50fa9d

# Yellow (Янтарные прожекторы)
color3  #e6b450
color11 #ffdb70

# Blue (Глубокий синий/сланец, для контраста)
color4  #4d80bd
color12 #7aa5d9

# Magenta (Пурпурный отблеск верхних ламп)
color5  #b566a8
color13 #e08cd1

# Cyan (Яркий "электрический" бирюзовый/неон)
color6  #30dff0
color14 #8be9fd

# White (Светло-серый и яркий белый)
color7  #b8c2bd
color15 #ffffff

# Прозрачность
background_opacity 0.6

# Размеры
initial_window_width  190c
initial_window_height 40c


include ~/.config/kitty/current-theme.conf
# Автозапуск neofetch
# shell zsh -c "wmctrl -r :ACTIVE: -e 0,30,120,-1,-1; fastfetch; exec zsh"

# Разрешаем удаленное управление для обновления цветов на лету (colorice)
allow_remote_control yes
listen_on unix:/tmp/kitty
