bold_font        auto
italic_font      auto
font_size        12.0
enable_audio_bell yes
initial_window_position top_left_left

background               #0b1210
foreground               #e0ebe8
cursor                   #ffae00
selection_background     #2d5c55
selection_foreground     #ffffff

color0  #1c2924
color8  #3a4f48

color1  #e05f45
color9  #ff7a63

color2  #20c278
color10 #50fa9d

color3  #e6b450
color11 #ffdb70

color4  #4d80bd
color12 #7aa5d9

color5  #b566a8
color13 #e08cd1

color6  #30dff0
color14 #8be9fd

color7  #b8c2bd
color15 #ffffff

background_opacity 0.6

initial_window_width  190c
initial_window_height 40c

include ~/.cache/wal/colors-kitty.conf
